const audio = [

  {
    artist: "Rabbi Krasnjanski",
    title: "Insights on the Hagada",
    url: "insights-on-the-hagada.mp3",
    description: "",
    tags: "pesach hagada passover holidays",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Asara Harugei Malchus",
    url: "asara-harugei-malchos.mp3",
    description: "",
    tags: "asara harugei malchus 10 martyrs",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Stories in Tanach",
    url: "Tanach-did-the stories-happen.mp3",
    description: "Did the stories in Tanach happen",
    tags: "Torah neviim kesovim tanach story stories",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Zos Chanucha",
    url: "Zos Chanukah Farbrengen with Rabbi Mendel Krasnjanski.mp3",
    description: "",
    tags: "holiday",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Yud Kislev",
    url: "10-kisslev.mp3",
    description: "",
    tags: "holiday yud kisslev yud kislev rebbe chabad lubavitcher miteler rebbe",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Vayera",
    url: "Vayera-2020-1.mp3",
    description: "",
    tags: "",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Bereshis, Noach",
    url: "audio/kraz/noach.mp3",
    description: "How did the snake speak with Chava",
    tags: "animals humans noach snake bereshis chava tree of life nachush shaton satan adam",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Pesach Matzah & Maror",
    url: "audio/kraz/Whoever doesn't mention pesach matzah and morar on pesach.mp3",
    description: "Whoever dosn't mention pesach matzah and maror on Pesach hasn't fulfilled their obligation",
    tags: "Holidays Pesach Mitzrayim pesach matzah maror",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Remember Leaving Mitzrayim",
    url: "audio/kraz/y2mate_com_Rabbi_Mendel_Krasnjanski_The_Age_Old_Puzzling_Rambam.mp3",
    description: " ",
    tags: "Holidays Pesach Mitzrayim",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Thanking Hashem",
    url: "audio/kraz/y2mate_com_Rabbi_Mendel_Krasnjanski_Magid_The_Huge_Thank_You_5nmDbtq24oM.mp3",
    description: "The theme of the seder night is to thank Hashem",
    tags: "Holidays Pesach",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Leaving Mitzrayim",
    url: "audio/kraz/y2mate_com_Rabbi_Mendel_Krasnjanski_How_To_Explain_Ben_Zoimo_jYpXuzl4KkE.mp3",
    description: "The diffrence between the Mitzvah to rember leaving mitzryim throughout the year and on Pesach",
    tags: "Holidays Pesach Mitzrayim",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Women & Haggadah",
    url: "audio/kraz/y2mate_com_Rabbi_Mendel_Krasnjanski_Women_&_Haggadah,_The_Big_Conundrum.mp3",
    description: " ",
    tags: "Holidays Pesach Women",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "The Backstory of Purim",
    url: "audio/kraz/backstory of purim 2020.mp3",
    description: "The events leading up to the the story of Purim",
    tags: "History Purim Holidays nevuchadnetzar achashverush",
  },
  {
    artist: "Mendel Presscott",
    title: "Living In Egypt",
    url: "audio/presscott/living in egypt.mp3",
    description: "How was the Rambam and other great sages allowed to live in Egypt",
    tags: "Halacha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Bo",
    url: "audio/kraz/bo-2020.mp3",
    description: "The children of Efraim who left Egypt 30 years early and were all killed",
    tags: "Parsha bo parshat bo shevet efraim plishtim",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Shemos",
    url: "audio/kraz/shmos2020.mp3",
    description: "Was Moshe Born a Tzaddik or did he have to work on himself",
    tags: "Parsha shemos shmos Shemot Moshe Moses Arabia King Palm Reading Face Reading",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Vayechi",
    url: "audio/kraz/vayechi-2020.mp3",
    description: "The embalming of Yaakov and Yosef",
    tags: "Parsha Vayechi Jacob Joseph",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Vayeshev",
    url: "audio/kraz/vayeshev-2020.mp3",
    description: "The Shevatims rational for selling Yosef",
    tags: "Parsha Vayeishev Vayesheb Joseph The 10 Martyrs Asarah Harugay Malchut Malchus",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Vayishlach",
    url: "audio/kraz/vayishlach.mp3",
    description: "Shimon and Levi massacred the city of Shechem, what was their justification and what was Yaakov's thoughts on the matter",
    tags: "Parsha Dina Gerim Gerrus converts converting",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Toldos - Yaakov & Esuv",
    url: "audio/kraz/toldos.mp3",
    description: "Does bechoros (first born) follow conception or birth",
    tags: "Parsha Vilna Goan Moses Mendelson tzemach tedek alter rebbe shloma ager yosef dina taz rabbenu gersun",
  },
  {
    artist: "Mendel Presscott",
    title: "Rav Simcha Bunim of Pesischa",
    url: "audio/presscott/simcha-bunim.mp3",
    description: "His early life before become a Rebbe",
    tags: "History",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Cherim on learning philosophy",
    url: "audio/kraz/ChachmasChetzunes.mp3",
    description: "",
    tags: "History Reshonim Rashba Rambam Ramban Rabbenu Yona Ra’ah Raah Aharon halevi",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Vayera - The atrocities of Sedom",
    url: "audio/kraz/Sedom.mp3",
    description: "Similarities between Sedom and an Ir Hanedachas (condemned city)",
    tags: "Parsha sodom and gomorrah lot",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "The four captives",
    url: "audio/kraz/history.four.captives.mp3",
    description: "The four captives and the spread of Torah from Bavel to the rest of the world",
    tags: "History Four captives Bulan Kuzari Kazar kingdom Rav hai Goan Rav Yosef Stanish Goanim Shmuel hanagid reshonim",
  },
  {
    artist: "Mendel Presscott",
    title: "Seeing a concentration camp",
    url: "audio/presscott/making a blessing upon seeing a concentration camp.mp3",
    description: "Making a blessing upon seeing a concentration camp",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Seeing a friend (1)",
    url: "audio/presscott/making a bracha upon seeing a friend part 1.mp3",
    description: "Making a blessing upon seeing a friend",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Seeing a friend (2)",
    url: "audio/presscott/making a bracha upon seeing a friend part 2.mp3",
    description: "Making a blessing upon seeing a friend",
    tags: "Halacha",
  },

  {
    artist: "Mendel Presscott",
    title: "Kohen & Medical School (1)",
    url: "audio/presscott/may a Cohn attend medical school 1.mp3",
    description: "May a Kohen attend medical school",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Kohen & Medical School (2)",
    url: "audio/presscott/may a Cohn attend medical school 2.mp3",
    description: "May a Kohen attend medical school",
    tags: "Halacha",
  },

  {
    artist: "Mendel Presscott",
    title: "killing bugs",
    url: "audio/presscott/killing bugs.3gp.mp3",
    description: "killing bugs in Halacha",
    tags: "Halacha",
  },

  {
    artist: "Mendel Presscott",
    title: "Mitzvah Yisuv E.Y. (1)",
    url: "audio/presscott/mitzvah yisuv ey part 1.3gp.mp3",
    description: "",
    tags: "Halacha",
  },

  {
    artist: "Mendel Presscott",
    title: "Mitzvah Yisuv E.Y. (2)",
    url: "audio/presscott/mitzvahs yisuv ey part 2.3gp.mp3",
    description: "",
    tags: "Halacha",
  },

  {
    artist: "Mendel Presscott",
    title: "Holocaust Responsa (1)",
    url: "audio/presscott/responsa from the Holocaust part 1.3gp.mp3",
    description: "",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Holocaust Responsa (2)",
    url: "audio/presscott/responsa from the Holocaust part 2 suicide part 1.mp3",
    description: "",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Holocaust Responsa (3)",
    url: "audio/presscott/responsa from the Holocaust part 3 suicide part 2.mp3",
    description: "",
    tags: "Halacha",
  },


  {
    artist: "Mendel Presscott",
    title: "kohen & Hospitals",
    url: "audio/presscott/is a kohen permitted to go to the hospital_.mp3",
    description: "Is a Kohen permitted to go to the Hospital",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Kohen & Dentist",
    url: "audio/presscott/is a kohen permitted to go to the dentist.3gp.mp3",
    description: "Is a Kohen permitted to go to the Dentist",
    tags: "Halacha",
  },


  {
    artist: "Mendel Presscott",
    title: "Living in Egypt (1)",
    url: "audio/presscott/living in Egypt part 1.mp3",
    description: "",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Living in Egypt (2)",
    url: "audio/presscott/living in Egypt part 2.mp3",
    description: "",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Living in Egypt (3)",
    url: "audio/presscott/living in Egypt part 3.mp3",
    description: "",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Living in Egypt _4",
    url: "audio/presscott/living in Egypt part 4.mp3",
    description: "",
    tags: "Halacha",
  },

  {
    artist: "Mendel Presscott",
    title: "Impeach a President",
    url: "audio/presscott/how to halachikly impeach a president part 1.mp3",
    description: "How to Halachikly impeach a President",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Hypnotism",
    url: "audio/presscott/hypnotism in halacha.3gp.mp3",
    description: "Hypnotism in Halacha",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Golam & A.I.",
    url: "audio/presscott/Golam.A.I.mp3.mp3",
    description: "Can a Golam or A.I. be counted for a minyan",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Giving presents",
    url: "audio/presscott/giving presents.mp3",
    description: "",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Dreams",
    url: "audio/presscott/dreams.mp3",
    description: "",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Credit unions",
    url: "audio/presscott/credit unions in halacha.mp3",
    description: "Credit unions in halacha",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "3-d printing  (1)",
    url: "audio/presscott/3-d printing in halacha part 1.mp3",
    description: "3-d printing in Halacha",
    tags: "Halacha",
  },
  {
    artist: "Mendel Presscott",
    title: "Cosmetic surgery",
    url: "audio/presscott/cosmetic surgery.mp3",
    description: "Cosmetic surgery in Halacha",
    tags: "Halacha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Lech Lecha - The First Jew",
    url: "audio/kraz/the.first.jew.mp3",
    description: "A discussion regarding who was the first Jew",
    tags: "Torah Jews Avraham Matan Torah Mitzvah Bnei Noach",
  },
  {
    artist: "Mendel Presscott",
    title: "The Maiden of Ludmir",
    url: "audio/presscott/The.maiden.of.ludmir.mp3",
    description: "Women and Chassidus",
    tags: "History Chassidim",
  },
  {
    artist: "Mendel Presscott",
    title: "The Baal Shem Tov (1)",
    url: "audio/presscott/theBaalshem-tovpart1.mp3",
    description: "Historical context in which the Ba'al Shem Tov entered Jewish history",
    tags: "History Chassidim",
  },
  {
    artist: "Mendel Presscott",
    title: "The Baal Shem Tov (2)",
    url: "audio/presscott/The-Ba'al-shem-tov-part2.mp3",
    description: "Historical context in which the Ba'al Shem Tov entered Jewish history",
    tags: "History Chassidim Miracles",
  },
  {
    artist: "Mendel Presscott",
    title: "Sfardim and Ashkazim",
    url: "audio/presscott/thedifferencebetweenSfardimandashkaziminthereapproachtomachlokes.mp3",
    description: "The difference between Sfardim and Ashkazim in their approach to machlokes",
    tags: "History",
  },
  {
    artist: "Mendel Presscott",
    title: "Early Rishonim (1)",
    url: "audio/presscott/earlySpanishRishonimfourcaptives.mp3",
    description: "Early Spanish Rishonim, the four captive's",
    tags: "History",
  },
  {
    artist: "Mendel Presscott",
    title: "Early Rishonim (2)",
    url: "audio/presscott/theearlyRishonimpart2.mp3",
    description: " ",
    tags: "History",
  },
  {
    artist: "Mendel Presscott",
    title: "The Baalei HaTosfos",
    url: "audio/presscott/TheBaaleiHaTosfos.mp3",
    description: "Discussion of the Mesorah - The Ba'alei HaTosfos",
    tags: "History Baalei HaTosfos",
  },
  {
    artist: "Mendel Presscott",
    title: "Rashi",
    url: "audio/presscott/Rashi.mp3",
    description: "Learn about the development and thought process that went into the making of a classic Torah commentary",
    tags: "History",
  },
  {
    artist: "Mendel Presscott",
    title: "The Gaonim",
    url: "audio/presscott/historyofthegaonim.mp3",
    description: "History of the Gaonim",
    tags: "History",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Shavous",
    url: "audio/kraz/shavous.mp3",
    description: "Why is it costomary to eat dairy on shavous",
    tags: "Holidays Shavous Matan Torah",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Bamidbar - Shavous",
    url: "audio/kraz/bamidbar-shavous.mp3",
    description: "Why didn't Ben Azzai need to fulfill the mitzvah of having children",
    tags: "Holidays Parsha Shavous Matan Torah",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Bechukoisai",
    url: "audio/kraz/bechukoisai.mp3",
    description: "I make plans to go places but I always end up at the study hall, Dovid Hamelech said to Hashem",
    tags: "Dovid Hamelech King God Hashem Study Hall Beis Medrash parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Tazria & Metzora (1)",
    url: "audio/kraz/tazria-metzora1.mp3",
    description: "What's the logic that the listener to lashun harah gets a greater punishment than the teller?",
    tags: "Loshan Harah parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Tazria & Metzora (2)",
    url: "audio/kraz/tazria-metzora2.mp3",
    description: "What's the logic that the listener to lashun harah gets a greater punishment than the teller?",
    tags: "Loshan Harah parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Pesach",
    url: "audio/kraz/pesach.mp3",
    description: "Everyday we have to remember leaving Egypt, what’s special about Pesach?",
    tags: "Leaving egypt yetzeas mitzrayim peshach holidays",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Behar",
    url: "audio/kraz/behar.mp3",
    description: "Understanding אונס with accountability",
    tags: "אונס parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Purim",
    url: "audio/kraz/purim.mp3",
    description: "Reasons for sending mishloach manos",
    tags: "holidays",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Shemini",
    url: "audio/kraz/shemene.mp3",
    description: "Why where Aharon's children punished if they where under 20",
    tags: "parsha accountability twenty",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Mishpatim",
    url: "audio/kraz/mishpatim.mp3",
    description: "Being Jewish vrs the Torah's laws of majority",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Mishpatim",
    url: "audio/kraz/mishpatim-1.mp3",
    description: "Matan Torah and Jewish conversion",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Yisro",
    url: "audio/kraz/yisro.mp3",
    description: "Question if Moshe was considered a king",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Bo",
    url: "audio/kraz/bo.mp3",
    description: "Story of moshe and the king of Arabia",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "The Rambam",
    url: "audio/kraz/rambam.mp3",
    description: "The Rambam's birth and who was his teacher",
    tags: "shemos chaf teves yehudah hacohen yosef halevi iben megash remegash tzadik rif",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Toldos",
    url: "audio/kraz/Rabbi_krav_toldus.mp3",
    description: "Did Yitzchak know that Esuv was up to no good?",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Vayera",
    url: "audio/kraz/Rabbi_kraz_vaera.mp3",
    description: "Can an Angel do more than one mission at a time and the connection between Lot and Mashiach",
    tags: "parsha Lot Mashiach Dovid King David shmuel moav moab",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Yud Tes Kislev",
    url: "audio/kraz/Rabbi_Kraz_pre_Yud_tes_kisslev.mp3",
    description: " ",
    tags: "holidays chassidish farbrengen",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Lech Lecha",
    url: "audio/kraz/Rabbi_kraz_lechlecha.mp3",
    description: "Is a father obligated to circumcise his son once the son turns thirteen",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Sukkos",
    url: "audio/kraz/Rabbi_kraz_suchos.mp3",
    description: "Were the Jews in the desert surrounded by clouds or actual Sukkos",
    tags: "Holidays",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Rosh Hashana",
    url: "audio/kraz/Rabbi_kraz_rush_hashana.mp3",
    description: "Is it allowed to fast on Rosh Hashana or not",
    tags: "Holidays",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Ki Savo",
    url: "audio/kraz/Rabbi_kraz_ke_savo.mp3",
    description: "Why did the Rabbis institute blessings before doing mitzvos",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Ki Savo",
    url: "audio/kraz/Rabbi_kraz_chai_elul_ke_savo.mp3",
    description: "Blessings on mitzvos, are they part of the mitzvos or mitzvos themselves",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Ki Seitzei",
    url: "audio/kraz/Rabbi_kraz_ke_tetze.mp3",
    description: "The reasoning behind the argument of 40 and 39 lashes",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Ki Seitzei",
    url: "audio/kraz/Rabbi_kraz_rushashana_ke_tzetze.mp3",
    description: "Do we punish someone now for future actions",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Shoftim",
    url: "audio/kraz/Rabbi_kraz_shuftim.mp3",
    description: "Eglah arufah",
    tags: "parsha revenge worms",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Shoftim",
    url: "audio/kraz/Rabbi_kraz_shuftim_2.mp3",
    description: "The seven Nations were kicked out of Israel for partaking in sorcery etc. why was this an issue for them?",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Vaeschanan",
    url: "audio/kraz/Rabbi_kraz_veschanun.mp3",
    description: "A father has an obligation to teach his son Torah",
    tags: "parsha mitzvas aseh coerce reward beis din tzedakah",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Vayeishev",
    url: "audio/kraz/vayeshev.mp3",
    description: "Yosef's brothers sell him and the connection to the asara harugei malchus",
    description: "The asara harugei malchus and their connection to the selling of Yosef by his brothers",
    tags: "parsha 10 ten martyrs shevatim tribs measure for measure middah keneged middah",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Miketz",
    url: "audio/kraz/meketz.mp3",
    description: "What was the mistake the Shevatim made in Judging Yosef",
    tags: "parsha Judge Judging",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Miketz",
    url: "audio/kraz/meketz_2.mp3",
    description: "Why did Yosef play games with his brothers even though it caused pain to his brothers and father",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Vayechi",
    url: "audio/kraz/vayechi.mp3",
    description: "Who actually killed Esuv",
    tags: "parsha mearas hamachpelah yaakov",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Vayechi",
    url: "audio/kraz/vayechi_2.mp3",
    description: "If one has intentions to commit a sin but don't actually carry through with it do they need atonement",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Parshas Vayechi",
    url: "audio/kraz/Vayechi_3.mp3",
    description: "Did Yosef actually forgive his brothers",
    tags: "parsha",
  },
  {
    artist: "Rabbi Krasnjanski",
    title: "Kebud Av",
    url: "audio/kraz/kebud_av.mp3",
    description: "Which comes first, honoring your father, mother or grandparents",
    tags: "parsha",
  },
];










